I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 17, in script call
    call scene_1
  File "game/story/Act1/scene_1.rpy", line 261, in script
    # Broadcast bell rings
Exception: Sayer 'Broadcast' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 17, in script call
    call scene_1
  File "game/story/Act1/scene_1.rpy", line 261, in script
    # Broadcast bell rings
  File "C:\Users\akank\OneDrive\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\akank\OneDrive\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Broadcast' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.1.23060707
Echoes Beyond The Gate 1.0
Fri Nov  3 03:03:43 2023
